---
- name: Get release information based on Git tags and GitHub releases
  block:

    - name: INFO  ----  List repositories
      ansible.builtin.debug:
        msg: "Repo URL = {{ github }}:{{ item.org }}/{{ item.repo }}"
      loop: "{{ repositories }}"
      # loop_control:
      #   label: "Repo to check = {{ github }}:{{ item.org }}/{{ item.repo }}.git"

    - name: INFO  ----  Query GitHub API
      ansible.builtin.command:
        cmd: "gh api repos/{{ item.org }}/{{ item.repo }}/releases"
      register: response
      loop: "{{ repositories }}"

    - name: INFO  ----  Display release information
      ansible.builtin.debug:
        msg:
          - "Repository: {{ item.org }}/{{ item.repo }}"
          - "Latest release: {{ (response.results[ansible_loop.index0].stdout | from_json)[0].tag_name | default('No releases') }}"
          - "Published at: {{ (response.results[ansible_loop.index0].stdout | from_json)[0].published_at | default('N/A') | regex_replace('T.*', '') }}"
      loop: "{{ repositories }}"
      loop_control:
        extended: true
