---
- name: Get release information based on Git tags and GitHub releases
  vars:
    versions_file: versions.md
  block:

    - name: INFO  ----  List repositories
      ansible.builtin.debug:
        msg: "Repo URL = {{ github }}:{{ item.org }}/{{ item.repo }}"
      loop: "{{ repositories }}"
      # loop_control:
      #   label: "Repo to check = {{ github }}:{{ item.org }}/{{ item.repo }}.git"

    - name: INFO  ----  Query GitHub API
      ansible.builtin.command:
        cmd: "gh api repos/{{ item.org }}/{{ item.repo }}/releases"
      register: response
      loop: "{{ repositories }}"

    - name: INFO  ----  Parse and set release facts
      ansible.builtin.set_fact:
        json: "{{ json | default([]) + [{'tag_name': (response.results[ansible_loop.index0].stdout | from_json)[0].tag_name | default('n/a'), 'published_date': (response.results[ansible_loop.index0].stdout | from_json)[0].published_at | default('N/A') | regex_replace('T.*', '')}] }}"
      loop: "{{ repositories }}"
      loop_control:
        extended: true

    - name: INFO  ----  Display release information
      ansible.builtin.debug:
        msg:
          - "Repository: {{ item.org }}/{{ item.repo }}"
          - "Latest release: {{ json[ansible_loop.index0].tag_name }}"
          - "Published at: {{ json[ansible_loop.index0].published_date }}"
      loop: "{{ repositories }}"
      loop_control:
        extended: true

    - name: INFO  ----  Remove {{ versions_file }}
      ansible.builtin.file:
        path: "{{ versions_file }}"
        state: absent

    - name: INFO  ----  Create {{ versions_file }}
      ansible.builtin.copy:
        dest: "{{ versions_file }}"
        content: |
          # Release Versions

          | Repository | Published Date | Latest Release |
          |:-----------|---------------:|---------------:|
        mode: u=rw,g=r,o=r

    - name: INFO  ----  Write release data to {{ versions_file }}
      ansible.builtin.lineinfile:
        path: "{{ versions_file }}"
        line: "| [{{ github }}/{{ item.org }}/{{ item.repo }}]({{ item.org }}/{{ item.repo }}) | {{ json[ansible_loop.index0].published_date }} | {{ json[ansible_loop.index0].tag_name }} |"
        insertafter: EOF
      loop: "{{ repositories }}"
      loop_control:
        extended: true
